name: Cypress Test
on:
  push:
    branches:
    - main
    - release/*

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Cypress run
      - uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          record: true
        env:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

